### ISSUE TITLE
Fix the nullable parameter declarations for compatibility with PHP 8.4

### ISSUE THREAD

**Issue by martio** [yiisoft/translator#144]
Hi! :smiley:

I have prepared a [small fix](https://github.com/yiisoft/translator/pull/142) that resolves the following issue:

```
DEPRECATED  Yiisoft\Translator\TranslatorInterface::translate(): Implicitly marking parameter $locale as nullable is deprecated, the explicit nullable type must be used instead in vendor/yiisoft/translator/src/TranslatorInterface.php on line 46.
```

`Yiisoft\Translator\TranslatorInterface`

```php
   public function translate(
       string|Stringable $id,
       array $parameters = [],
       string $category = null,
       string $locale = null
   ): string;
```

### What steps will reproduce the problem?

Attempt to use the `Yiisoft\Translator\TranslatorInterface::translate` method in a PHP 8.4 environment without explicitly declaring nullable types for parameters like $locale.

### What is the expected result?

The translate method should function without deprecation warnings, and the application should remain compatible with PHP 8.4.

### What do you get instead?

A deprecation warning is triggered:
`DEPRECATED: Yiisoft\Translator\TranslatorInterface::translate(): Implicitly marking parameter $locale as nullable is deprecated, the explicit nullable type must be used instead in vendor/yiisoft/translator/src/TranslatorInterface.php` on line 46.`

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 2.1.0
| PHP version      |  8.4.1
| Operating system | Unix

**Comment by vjik** [comment]
Done by #148
