### ISSUE TITLE
Alias "t" for translate()?

### ISSUE THREAD

**Issue by tomaszkane** [yiisoft/translator#38]
Question:
Is adding alias for `translate()` https://github.com/yiisoft/translator/blob/master/src/TranslatorInterface.php#L44 is a good idea?
Why not?

`$translator->translate()` vs `$translator->t()`

**Comment by samdark** [comment]
1. It makes interface ambigous. User has to thing about which method to use.
2. While shorter, it's not explanative.
3. We may introduce a shortcut in the future, still thinking about it. But that won't be part of this interface anyway.
