### ISSUE TITLE
Use Yii formatter for formatting message patterns

### ISSUE THREAD

**Issue by cebe** [yiisoft/translator#4]
### What steps will reproduce the problem?

Citing from slack:

> why `echo \Yii::t('app', 'Price: {0,number,currency}', $price);`
not calling `Yii::$app->formatter->asCurrency`
at the result the `{0,number,currency}` seem buggy

### What is the expected result?

For overall consistency formatters in messages should use what is configured in Yii and not use intl directly.

Not sure how exactly to implement it but it would be a good improvement.

**Comment by samdark** [comment]
Not applicable to current concept.
