### ISSUE TITLE
Omit some public methods from TranslatorInterface

### ISSUE THREAD

**Issue by xepozz** [yiisoft/translator#60]
I think that such methods as `addCategorySource`, `addCategorySources` and `withCategory` are not necessary in `TranslatorInterface`.
Translator may have it, but the interface is not about it. It should not matter how the translator configured. Only ability to translate is needed from the interface.
What about `getLocale`/`setLocale`/`withLocale` – it may very helpful to use translator in some middlewares, layouts or another similar things.
I'll make a PR and remove these methods from the interface.

**Comment by samdark** [comment]
> I think that such methods as addCategorySource, addCategorySources and withCategory are not necessary in TranslatorInterface.
> Translator may have it, but the interface is not about it. It should not matter how the translator configured. Only ability to translate is needed from the interface.

The use-case for these is providing an ability to add its own translation for third-party packages i.e. a package may add its own source via bootstrapping. An example is a "user" package that has some route handlers outputting HTML with translated strings.

> What about getLocale/setLocale/withLocale – it may very helpful to use translator in some middlewares, layouts or another similar things.

What's the issue with these?

**Comment by samdark** [comment]
`withLocale` is there to allow rendering multiple widgets with multiple different locales on the same page.

**Comment by xepozz** [comment]
> What's the issue with these?
No issues, just said that it may be useful.

> `withLocale` is there to allow rendering multiple widgets with multiple different locales on the same page.
I haven't deleted it.

**Comment by samdark** [comment]
So overall:

1. Removing runtime configuration in this case is contraversial. If there were no released stable version, it might have worth it. Decision: leaving it for now as is.
2. The idea to have `addCaregories(...$categories)` instead of two methods is supported by majority of team members but isn't going to implement it right now since it doesn't improve things slightly and requires a major release.

**Comment by vjik** [comment]
Closed by #81
